import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { CONSENT_VERSION, checkedPhoto, nutrition, checkedItems, readRecognition, freeConfiguration, recognitionRequest } from '../supabase/functions/meal-analysis/core.mjs';
const catalog=JSON.parse(readFileSync(new URL('../supabase/functions/meal-analysis/nutrition_catalog.json',import.meta.url),'utf8'));
const food={name:'Arroz',food_id:'169757',grams:150,confidence:'high'};
assert.equal(nutrition([food],catalog).totals.kcal,195);
assert.equal(nutrition([food],catalog).totals.protein_g,4);
assert.equal(nutrition([{...food,grams:50}],catalog).totals.kcal,65);
assert.equal(nutrition([{...food,food_id:'invented'}],catalog).missing,1);
assert.equal(nutrition([{...food,grams:0}],catalog).complete,false);
for(const grams of [-1,2001,NaN,Infinity,'100',true]) assert.throws(()=>checkedItems([{...food,grams}],catalog));
assert.throws(()=>nutrition([],catalog));
assert.throws(()=>nutrition(Array(13).fill(food),catalog));
assert.throws(()=>readRecognition({is_food_photo:true,contains_personal_content:true,items:[food]},catalog));
assert.throws(()=>readRecognition({is_food_photo:false,contains_personal_content:false,items:[food]},catalog));
assert.throws(()=>freeConfiguration(()=>''));
assert.throws(()=>freeConfiguration(key=>({GEMINI_API_KEY:'test',GEMINI_FREE_TIER_CONFIRMED:'true',GEMINI_MEAL_MODEL:'paid-model'}[key]||'')));
assert.equal(freeConfiguration(key=>({GEMINI_API_KEY:'test',GEMINI_FREE_TIER_CONFIRMED:'true'}[key]||'')),'gemini-3.8-flash');
const request=recognitionRequest('image',catalog);
assert.equal(request.contents[0].parts[0].inlineData.data,'image');
assert.equal(request.generationConfig.responseMimeType,'application/json');
assert.equal(request.tools,undefined);
assert.equal(request.cachedContent,undefined);
// Small synthetic JPEG header suffices to test metadata/size validation, not image inference.
const jpg=Buffer.from([255,216,255,192,0,11,8,0,10,0,10,1,1,17,0,255,218,0,2,255,217]).toString('base64');
const body={consent_version:CONSENT_VERSION,adult:true,mime_type:'image/jpeg',image:jpg};
assert.equal(checkedPhoto(body),jpg);
assert.throws(()=>checkedPhoto({...body,adult:false}));
assert.throws(()=>checkedPhoto({...body,image:'no-image'}));
assert.throws(()=>checkedPhoto({...body,image:Buffer.from([255,216,255,225,0,4,0,0,255,217]).toString('base64')}));
assert(catalog.every(row=>row.name && row.id && row.source_url.startsWith('https://fdc.nal.usda.gov/') && Object.values(row.per100).every(Number.isFinite)));
console.log('Meal backend: input validation, privacy, free-only configuration and deterministic nutrition passed.');
