// In-memory PostgreSQL contract test. No network, credentials, or production data.
const {PGlite} = require(process.env.SOLEM_PGLITE_MODULE || '@electric-sql/pglite');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
 const db = new PGlite();
 await db.exec(`create role anon; create role authenticated;
 create schema auth; create schema storage;
 create table auth.users(id uuid primary key);
 insert into auth.users values ('11111111-1111-1111-1111-111111111111'),('22222222-2222-2222-2222-222222222222');
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth,storage,public to anon,authenticated;
 grant execute on function auth.uid() to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id serial primary key,bucket_id text,name text);
 alter table storage.objects enable row level security;
 create policy unrelated_broad_policy on storage.objects for all to anon,authenticated using(true) with check(true);
 grant select,insert,update,delete on storage.objects to anon,authenticated;
 grant usage on sequence storage.objects_id_seq to anon,authenticated;`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260907_personal_workspace.sql'),'utf8'));
 const userA='11111111-1111-1111-1111-111111111111', userB='22222222-2222-2222-2222-222222222222';
 const note='33333333-3333-3333-3333-333333333333', pdf='44444444-4444-4444-4444-444444444444';
 const asUser=async user => { await db.exec('reset role; set role authenticated'); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]); };
 await asUser(userA);
 await db.query("insert into public.solem_items(id,kind,title,body) values ($1,'note','Nota','Privada')",[note]);
 await db.query("insert into public.solem_items(id,kind,title) values ($1,'pdf','PDF privado')",[pdf]);
 assert.equal((await db.query('select file_path from public.solem_items where id=$1',[pdf])).rows[0].file_path,`${userA}/${pdf}.pdf`);
 await db.query("insert into storage.objects(bucket_id,name) values ('solem-documents',$1)",[`${userA}/${pdf}.pdf`]);
 await assert.rejects(db.query("insert into public.solem_items(id,kind,title,duration_minutes,event_date) values ('55555555-5555-5555-5555-555555555555','plan','Inválido',0,'2026-09-07')"));
 await assert.rejects(db.query("insert into public.solem_items(id,kind,title,body) values ('55555555-5555-5555-5555-555555555555','mindmap','Mapa',E'Raiz\\n    Salto')"));
 await asUser(userB);
 assert.equal((await db.query('select * from public.solem_items')).rows.length,0);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 assert.equal((await db.query("update public.solem_items set title='Ataque' where id=$1 returning id",[note])).rows.length,0);
 await assert.rejects(db.query("insert into public.solem_items(id,owner_id,kind,title) values ('55555555-5555-5555-5555-555555555555',$1,'note','Ataque')",[userA]));
 await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values ('solem-documents',$1)",[`${userA}/${pdf}.pdf`]));
 await asUser(userA);
 const saved=await db.query("update public.solem_items set title='Editada' where id=$1 and revision=1 returning revision",[note]);
 assert.equal(saved.rows[0].revision,2);
 assert.equal((await db.query("update public.solem_items set title='Obsoleta' where id=$1 and revision=1 returning id",[note])).rows.length,0);
 await assert.rejects(db.query('update public.solem_items set owner_id=$1 where id=$2',[userB,note]));
 await db.query('update public.solem_items set archived=true where id=$1',[pdf]);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await db.query('update public.solem_items set archived=false where id=$1',[pdf]);
 assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 assert.equal((await db.query("update storage.objects set name='overwritten.pdf' returning id")).rows.length,0);
 assert.equal((await db.query('delete from storage.objects returning id')).rows.length,0);
 await db.exec("reset role; set role anon; select set_config('request.jwt.claim.sub','',false)");
 await assert.rejects(db.query('select * from public.solem_items'));
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await db.close();
 console.log('PASS: migration, constraints, ownership isolation, private PDF access, optimistic revision, archive/restore, anonymous denial.');
})().catch(error => { console.error(error); process.exitCode=1; });
